receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

extensions:
  health_check: {}

exporters:
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  debug:
    verbosity: detailed
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp/logs, debug ]
    metrics:
      receivers: [ otlp ]
      exporters: [ otlphttp/prometheus, debug ]